"""add catalog_items

Revision ID: 4ac46f8005b9
Revises: 3f2a9d8c7b11
Create Date: 2026-02-28 14:23:03.414212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ac46f8005b9'
down_revision: Union[str, None] = '3f2a9d8c7b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_items_tenant_id'), 'catalog_items', ['tenant_id'], unique=False)
    op.drop_index('ix_sales_earn_events_salesperson_occurred', table_name='salesperson_earning_events')
    op.drop_index('ix_sales_earn_events_tenant', table_name='salesperson_earning_events')
    op.drop_index('ix_sales_earn_events_type', table_name='salesperson_earning_events')
    op.drop_table('salesperson_earning_events')
    op.drop_index('ix_users_phone_e164', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_phone_e164', 'users', ['phone_e164'], unique=False)
    op.create_table('salesperson_earning_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('salesperson_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'KES'::character varying"), autoincrement=False, nullable=False),
    sa.Column('gross_amount', sa.NUMERIC(precision=12, scale=2), server_default=sa.text('0.00'), autoincrement=False, nullable=False),
    sa.Column('commission_amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=20), server_default=sa.text("'MANUAL'::character varying"), autoincrement=False, nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['salesperson_profile_id'], ['salesperson_profiles.id'], name='salesperson_earning_events_salesperson_profile_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='salesperson_earning_events_tenant_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='salesperson_earning_events_pkey')
    )
    op.create_index('ix_sales_earn_events_type', 'salesperson_earning_events', ['event_type'], unique=False)
    op.create_index('ix_sales_earn_events_tenant', 'salesperson_earning_events', ['tenant_id'], unique=False)
    op.create_index('ix_sales_earn_events_salesperson_occurred', 'salesperson_earning_events', ['salesperson_profile_id', 'occurred_at'], unique=False)
    op.drop_index(op.f('ix_catalog_items_tenant_id'), table_name='catalog_items')
    op.drop_table('catalog_items')
    # ### end Alembic commands ###
