"""feat(sales): attribution + earning ledger fields

Revision ID: 6ed7caee49fb
Revises: c700133bb19e
Create Date: 2026-02-16 19:57:33.293591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ed7caee49fb'
down_revision: Union[str, None] = 'c700133bb19e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_earn_events_salesperson_occurred', table_name='salesperson_earning_events')
    op.drop_index('ix_sales_earn_events_tenant', table_name='salesperson_earning_events')
    op.drop_table('salesperson_earning_events')
    op.drop_index('uq_platform_invitations_pending_email', table_name='platform_invitations', postgresql_where='(accepted_at IS NULL)')
    op.drop_constraint('platform_memberships_user_id_fkey', 'platform_memberships', type_='foreignkey')
    op.create_foreign_key(None, 'platform_memberships', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('uq_tenant_invites_pending_tenant_email', table_name='tenant_invitations', postgresql_where='(accepted_at IS NULL)')
    op.create_index('ix_tenant_invitations_tenant_created_at', 'tenant_invitations', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_tenant_invitations_tenant_email', 'tenant_invitations', ['tenant_id', 'email'], unique=False)
    op.create_index('ix_tenant_memberships_tenant_role', 'tenant_memberships', ['tenant_id', 'role'], unique=False)
    op.create_index('ix_tenant_memberships_user', 'tenant_memberships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tenant_memberships_user', table_name='tenant_memberships')
    op.drop_index('ix_tenant_memberships_tenant_role', table_name='tenant_memberships')
    op.drop_index('ix_tenant_invitations_tenant_email', table_name='tenant_invitations')
    op.drop_index('ix_tenant_invitations_tenant_created_at', table_name='tenant_invitations')
    op.create_index('uq_tenant_invites_pending_tenant_email', 'tenant_invitations', ['tenant_id', 'email'], unique=True, postgresql_where='(accepted_at IS NULL)')
    op.drop_constraint(None, 'platform_memberships', type_='foreignkey')
    op.create_foreign_key('platform_memberships_user_id_fkey', 'platform_memberships', 'users', ['user_id'], ['id'])
    op.create_index('uq_platform_invitations_pending_email', 'platform_invitations', [sa.text('lower(email::text)')], unique=True, postgresql_where='(accepted_at IS NULL)')
    op.create_table('salesperson_earning_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('salesperson_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'KES'::character varying"), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=20), server_default=sa.text("'MANUAL'::character varying"), autoincrement=False, nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['salesperson_profile_id'], ['salesperson_profiles.id'], name='salesperson_earning_events_salesperson_profile_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='salesperson_earning_events_tenant_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='salesperson_earning_events_pkey')
    )
    op.create_index('ix_sales_earn_events_tenant', 'salesperson_earning_events', ['tenant_id'], unique=False)
    op.create_index('ix_sales_earn_events_salesperson_occurred', 'salesperson_earning_events', ['salesperson_profile_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###
