"""add social platform accounts

Revision ID: 7ce9a53c6c77
Revises: ae490814a43e
Create Date: 2026-03-10 20:25:05.283313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ce9a53c6c77'
down_revision: Union[str, None] = 'ae490814a43e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_platform_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('social_connection_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('account_type', sa.String(length=64), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('provider_account_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('account_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_selected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['social_connection_id'], ['social_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_connection_id', 'provider_account_id', name='uq_social_platform_accounts_connection_provider_account')
    )
    op.create_index(op.f('ix_social_platform_accounts_platform'), 'social_platform_accounts', ['platform'], unique=False)
    op.create_index(op.f('ix_social_platform_accounts_social_connection_id'), 'social_platform_accounts', ['social_connection_id'], unique=False)
    op.create_index(op.f('ix_social_platform_accounts_tenant_id'), 'social_platform_accounts', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_platform_accounts_tenant_id'), table_name='social_platform_accounts')
    op.drop_index(op.f('ix_social_platform_accounts_social_connection_id'), table_name='social_platform_accounts')
    op.drop_index(op.f('ix_social_platform_accounts_platform'), table_name='social_platform_accounts')
    op.drop_table('social_platform_accounts')
    # ### end Alembic commands ###
