"""add subscription fields

Revision ID: 7f0ac360788c
Revises: ec4e1d24f27b
Create Date: 2026-04-24 08:39:09.671915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0ac360788c'
down_revision: Union[str, None] = 'ec4e1d24f27b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'uq_salesperson_earning_external_ref',
        'salesperson_earning_events',
        type_='unique'
    )

    # ✅ FIX: add server_default
    op.add_column(
        'tenants',
        sa.Column(
            'subscription_status',
            sa.String(length=30),
            nullable=False,
            server_default='trial'
        )
    )

    op.add_column(
        'tenants',
        sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True)
    )

    op.add_column(
        'tenants',
        sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'subscription_ends_at')
    op.drop_column('tenants', 'trial_ends_at')
    op.drop_column('tenants', 'subscription_status')
    op.create_unique_constraint('uq_salesperson_earning_external_ref', 'salesperson_earning_events', ['external_ref'])
    # ### end Alembic commands ###
