"""add social connections

Revision ID: ae490814a43e
Revises: 8b1d9f2e6c31
Create Date: 2026-03-10 14:41:00.546365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae490814a43e'
down_revision: Union[str, None] = '8b1d9f2e6c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('connected_by_user_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=True),
    sa.Column('provider_account_name', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('connection_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connected_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'platform', name='uq_social_connections_tenant_platform')
    )
    op.create_index(op.f('ix_social_connections_connected_by_user_id'), 'social_connections', ['connected_by_user_id'], unique=False)
    op.create_index(op.f('ix_social_connections_platform'), 'social_connections', ['platform'], unique=False)
    op.create_index(op.f('ix_social_connections_tenant_id'), 'social_connections', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_connections_tenant_id'), table_name='social_connections')
    op.drop_index(op.f('ix_social_connections_platform'), table_name='social_connections')
    op.drop_index(op.f('ix_social_connections_connected_by_user_id'), table_name='social_connections')
    op.drop_table('social_connections')
    # ### end Alembic commands ###
