"""add meta catalogs table

Revision ID: bcbca5afdff6
Revises: 5513b190f022
Create Date: 2026-03-26 20:06:36.096559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcbca5afdff6'
down_revision: Union[str, None] = '5513b190f022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_catalogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('catalog_id', sa.String(), nullable=False),
    sa.Column('catalog_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_catalogs_business_id'), 'meta_catalogs', ['business_id'], unique=False)
    op.create_index(op.f('ix_meta_catalogs_catalog_id'), 'meta_catalogs', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_meta_catalogs_id'), 'meta_catalogs', ['id'], unique=False)
    op.create_index(op.f('ix_meta_catalogs_tenant_id'), 'meta_catalogs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_catalogs_tenant_id'), table_name='meta_catalogs')
    op.drop_index(op.f('ix_meta_catalogs_id'), table_name='meta_catalogs')
    op.drop_index(op.f('ix_meta_catalogs_catalog_id'), table_name='meta_catalogs')
    op.drop_index(op.f('ix_meta_catalogs_business_id'), table_name='meta_catalogs')
    op.drop_table('meta_catalogs')
    # ### end Alembic commands ###
