"""add platform invitations and memberships

Revision ID: f30888e5800a
Revises: afe8cd3ef607
Create Date: 2026-02-14 09:26:30.015317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f30888e5800a'
down_revision: Union[str, None] = 'afe8cd3ef607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('invitee_type', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_invitations_email'), 'platform_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_platform_invitations_token'), 'platform_invitations', ['token'], unique=True)
    op.create_table('platform_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('accepted_terms', sa.Boolean(), nullable=False),
    sa.Column('notifications_opt_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_memberships_user_id'), 'platform_memberships', ['user_id'], unique=True)
    op.create_table('salesperson_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('referral_code', sa.String(length=6), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_payment_amount', sa.Integer(), nullable=True),
    sa.Column('last_payment_phone', sa.String(length=32), nullable=True),
    sa.Column('last_payment_assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salesperson_profiles_referral_code'), 'salesperson_profiles', ['referral_code'], unique=True)
    op.create_index(op.f('ix_salesperson_profiles_user_id'), 'salesperson_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salesperson_profiles_user_id'), table_name='salesperson_profiles')
    op.drop_index(op.f('ix_salesperson_profiles_referral_code'), table_name='salesperson_profiles')
    op.drop_table('salesperson_profiles')
    op.drop_index(op.f('ix_platform_memberships_user_id'), table_name='platform_memberships')
    op.drop_table('platform_memberships')
    op.drop_index(op.f('ix_platform_invitations_token'), table_name='platform_invitations')
    op.drop_index(op.f('ix_platform_invitations_email'), table_name='platform_invitations')
    op.drop_table('platform_invitations')
    # ### end Alembic commands ###
